suit cosmetics
randovania/open-prime-rando pull request #73
Opened 2023-07-28 08:59 UTC by duncathan

- [x] Player 2
- [ ] Player 3
- [ ] Player 4

2023-07-28 09:00 UTC, duncathan commented
Player 2
![image](https://github.com/randovania/open-prime-rando/assets/2979303/7a4449c2-b58b-4794-bad1-3d5661814c27)
![image](https://github.com/randovania/open-prime-rando/assets/2979303/c5f4bfe0-3f53-421e-a731-da0bb49c2f73)
![image](https://github.com/randovania/open-prime-rando/assets/2979303/a3119880-674b-4bbc-998f-54da36aebd85)

2023-07-28 10:20 UTC, henriquegemignani requested changes

2023-07-28 15:39 UTC, duncathan commented on src/open_prime_rando/echoes/schema.json
> +                    "varia": "player2",
yes

2023-08-02 03:41 UTC, duncathan commented
Player 3
![image](https://github.com/randovania/open-prime-rando/assets/2979303/f5a69fb3-8cad-424b-9a36-83595f56fe58)
![image](https://github.com/randovania/open-prime-rando/assets/2979303/1e890126-8756-4b8e-ac63-2e81461b60d5)
![image](https://github.com/randovania/open-prime-rando/assets/2979303/edf0b3d1-f245-49d7-9985-4245f80060c8)

2023-08-02 03:41 UTC, duncathan commented
Player 4
![image](https://github.com/randovania/open-prime-rando/assets/2979303/71454777-8936-4b0f-9466-98b7cca6f2ec)
![image](https://github.com/randovania/open-prime-rando/assets/2979303/dc975b86-afe9-4ae7-9d11-3934e89adcf7)
![image](https://github.com/randovania/open-prime-rando/assets/2979303/7ef0237a-247d-4662-8aaa-6552310e1957)

2023-08-02 20:27 UTC, henriquegemignani approved these changes

2023-08-02 20:36 UTC, merged